Select * from customer limit 20
--1. What is the total of renvenue generated by male vs female customer?
select gender ,sum(purchase_amount) as revenue from customer group by gender;

--2. which customer used a discount but still spent more than the average purchase amount
select customer_id , purchase_amount
from customer
where purchase_amount>=(select avg(purchase_amount) from customer) and discount_applied ='Yes';

--3. which are the top 5 products with the highest average review ratting
select item_purchased , round(avg(review_rating::numeric),2) as product_rating 
from customer
group by item_purchased 
order by avg(review_rating) desc
limit 5;

--4.compare the average the purcahse amounts between standard and express shipping
select shipping_type,
round(avg(purchase_amount),2) 
from customer 
where shipping_type in ('Standard' , 'Express')
group by shipping_type;


--5.Do subscriced customers spend more ? compare the average spend and total revenue between subscribe and non subscriber
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;
--6. which 5 product have the highest percentage of purchses with sicount applied

select item_purchased ,
round(100*sum(case when discount_applied ='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer

group by item_purchased
order by discount_rate desc
limit 5 ;

--6. Segment customer into new , returning and loyal based on their total number of previous purchase
with customer_type as
(select customer_id, previous_purchases,
CASE 
    WHEN previous_purchases =1 then 'New'
	WHEN previous_purchases BETWEEN 2 and 10 then 'Rerurning'
	ELSE 'Loyal'
	end as customer_segment
from customer
)

select customer_segment , count(*) as "Number of Customers"
from customer_type
group by customer_segment;

--8.what are the top 3 most purchased product within each category ?

with item_counts as (
select category , 
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over (partition by category order by count(customer_id) desc) as item_rank
from customer
group by category , item_purchased
)


-- select * from item_counts
select item_rank , category , item_purchased , total_orders
from item_counts
where item_rank <=3;


--9.are customer who are repeat buyers ( more than 5 previous purchases) also likely to subscribe
select count(customer_id) as repeat_buyers , subscription_status
from customer 
where previous_purchases>5 
group by subscription_status;

--10.what are the revenue contribution of each age group
select age_group , SUM(purchase_amount) as total_revenue
from customer 
group by age_group 
order by total_revenue desc;

 





